image: timbru31/docker-java-node:11-alpine

before_script:
  - npm install
  - npm install -g shadow-cljs
  - shadow-cljs release test-page

pages:
  stage: deploy

  script:
    - mkdir public
    - cp -r resources/public/* public
  artifacts:
    paths:
      - public
  only:
    - master

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/